force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Object used to retain all project records. Organize teams, activities and everything related to projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Object used to organize all team tasks into records.</description>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The Task related project.</description>
    <inlineHelpText>The Task related project.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TaskService.cls
public with sharing class TaskService {
   
    public void checkTaskName(List<Task__c> newTasks) {
        List<Task__c> updatedTasks = new List<Task__c>();

        for (Task__c task : newTasks) {
            if (task.Name == null || task.Name.trim() == '') {
                task.addError('O nome da tarefa é obrigatório.');
            }
            task.Name = task.Project__r.Name + '|TSK:' + task.Name;
        }
        update newTasks;
        System.debug('Método finalizado.');
    }

}